### ISSUE TITLE
Mirror schema's for fixture sets like Rails's "db/schema.rb"

### ISSUE THREAD

**Issue by joegoggins** [umn-asr/iron_fixture_extractor#2]
It would also be good if there were a rake task to inject the columns into the fixtures that reflect the current schema, to drop deleted columns, and something that could detect differents.

* An :extract_schema option passed to .extract that uses `rake db:structure:dump` functionality 
  or ActiveRecord::Base.connection.structure_dump to create .sql files containing a "create table" statement
  for each distinct model class.  This would allow you to completely de-couple your test cases + fixtures
  from the external databases they were extracted from.

**Comment by IanWhitney** [comment]
I'm going to close potential and enhancement issues for now. While we are maintaining this gem, we aren't looking to add new features. However, if someone wants to do a PR for something like this, they are welcome to do so.
