### ISSUE TITLE
Shall I do a PR to fix this Deprecation warning

### ISSUE THREAD

**Issue by tracymu** [umn-asr/iron_fixture_extractor#22]
DEPRECATION WARNING: ActiveRecord::Fixtures is deprecated! Use ActiveRecord::FixtureSet instead

**Comment by joegoggins** [comment]
Thanks for the offer @tracymu , at this point, this project has taken on a life of it's own and I am no longer maintaining it, so I don't think it'd do much good, :) I'm thinking the best thing would be to identify an owner who wants to own this tool and it's future.

I added collaborator access for @cbillen a while ago, but given the GitHub network graph revealing lots of forks + dev by @AndrewSwerlick @ryanricard @BlackFoks and @habanerohq . Perhaps one of them might want to step up to be the official owner, or I can just add them as collaborators to this repo too. 

Ideally, I'd love to see the niche that this tool fills be replaced by getting it's main functionality cooked into Rails proper, maybe there is scope to get this into Rails 5 as a fixture management tool, not sure. If you refactored the tool a bit to fully embrace factories (as hackily [illustrated here](https://github.com/joegoggins/iron_fixture_extractor#load-particular-fixture-into-memory-typically-used-to-instantiate-an-object-or-build-a-factory)) as well as fixtures, I could see lots of devs benefiting from being able to utilize real-world production data in their Rails test suites.

What do you say peeps? Any interested?

**Comment by prusswan** [comment]
I am using this in a Rails 3.2 project and evaluating its 'fitness' for Rails 4.1+ (for current support). Thankfully the changes required are not severe since this gem does not try to fight Rails internals too much. The concern as I raised in #21 remains however, since it forces a choice to be made between using the default fixtures, and custom fixtures.

**Comment by joegoggins** [comment]
I'd recommend looking at some of the downstream forks for use in a 4.1
context, this repo has not been updated to accommodate 4.x things and I'm
looking to transfer the tool ownership/maintenance role to someone (
perhaps one of the downstream folks ), if they are interested.

**Comment by ryanricard** [comment]
I would help out, but unfortunately I am not using iron_fixture_extractor at this time. @IanWhitney, are you still using this Gem? Perhaps you could help out. :smiling_imp:

**Comment by IanWhitney** [comment]
We have a 4.x ready branch. @joegoggins, if you pass this repo back to @umn-asr, we can do official releases and updates.

**Comment by joegoggins** [comment]
That is spectacular! Will transition this repo over to ya. Thanks Ian!

**Comment by joegoggins** [comment]
Hey Ian, twas trying to transfer this over and got a "denied, you must have admin rights on umn-asr to do this" message. It sounds like the way to do this if for the recipient organization to make a temp team with admin rights to the org, add me to it, then i do the transfer, then delete that team. This article describes the details: https://help.github.com/articles/transferring-a-repository/#transferring-from-a-user-to-an-organization.

Ping me once the permissions are in place and I'll give it another whirl!

**Comment by IanWhitney** [comment]
You should be set.

**Comment by joegoggins** [comment]
Sweet. Indeed, that worked. Great to know that this tool has a new home, owner, maintainer at https://github.com/umn-asr/iron_fixture_extractor . Thank you very much for stepping up to take on this role!

**Comment by ryanricard** [comment]
Glad to hear this project is in good hands. Thanks @IanWhitney for taking over the reigns!
