### ISSUE TITLE
Support ruby > 3

### ISSUE THREAD

**Issue by davinlagerroos** [umn-asr/iron_fixture_extractor#33]
This gem uses `YAML.load_file` as part of `Fe.get_hash` (and maybe other places). ActiveRecord models have date related fields that are not in the default Pysch permitted class list, raising errors.

**Comment by isen0011** [comment]
I don't want to put more effort into iron fixture, but I also think if we are going to keep using it we need it to work with Ruby 3.

**Comment by thoma127** [comment]
I'm on the fence. I don't really want to support this gem, but the alternative path is to extract ourselves from using it, which is _a lot_ of work.

**Comment by isen0011** [comment]
Do we have an issue/story for extracting ourselves from Iron Fixture?  Maybe we should prioritize that instead?

**Comment by dlagerro** [comment]
This is fixed in [a branch](https://github.com/umn-asr/iron_fixture_extractor/tree/ruby_3_2_rails_7), so I think this issue is closed. 

Admittedly a branch is not the best place for this, but cleaning up our branches and/or adding releases is a different issue.
