### ISSUE TITLE
Output should be more descriptive

### ISSUE THREAD

**Issue by joegoggins** [umn-asr/iron_fixture_extractor#4]
The details of what happened due to a particular command should inform the user what has changed rather than simply summarizing it in the fe_manifest.yml
We return a Fe::Extractor instance...it should implement a meaningful .inspect method for this issue to be done.

**Comment by IanWhitney** [comment]
I'm going to close potential and enhancement issues for now. While we are maintaining this gem, we aren't looking to add new features. However, if someone wants to do a PR for something like this, they are welcome to do so.
