### ISSUE TITLE
Aliases: should be able to define a fe_aliases.yml within fixture set

### ISSUE THREAD

**Issue by joegoggins** [umn-asr/iron_fixture_extractor#6]
Given a manually created file within a iron fixture set called "poo" like:

    fe_aliases.yml
      cla_audit: "1234567"
      cse_audit_w_honors: "7654321"

I should be able to do:

    Fe.alias(:poo,"cla_audit")

And see:

    "1234567"

I should also be able to do:

    Fe.set_alias(:poo,"another",44)

And it would write the yml hash like this:

    fe_aliases.yml
      cla_audit: "1234567"
      cse_audit_w_honors: "7654321"
      another: 44
    
And be able to do:

    Fe.alias(:poo,"another")

And see:

    44

Note that type IS preserved here, (i.e. 44 is an integer, not a string)

This feature would be handy for rolling up facts about particular data items within a fixture set, so test cases can reference these labels rather than the data itself.  Would greatly improve the readability of tests that use iron fixture extractor.

**Comment by IanWhitney** [comment]
Facts were introduced in eb3bd05 but I don't believe they were ever released as part of the gem. #28 re-introduces facts as part of the 1.2.0 release.
